"""全片 8 场 / 38 镜候选草案。前 8 镜（37 秒）为详细时间轴；其余为排演预算。"""
from __future__ import annotations

from planning import FPS, _reflow_timelines, recompute, seconds_to_frames

SEQUENCES = [
    {"id": "seq01", "order": 1, "title": "电话两端",
     "script_range": "0:00–0:21", "target_seconds": 21,
     "script_source": "0:00—0:21｜深夜，办公室×母亲家（电话两端）",
     "shot_ids": ["sh001", "sh002", "sh003", "sh004", "sh005"]},
    {"id": "seq02", "order": 2, "title": "工位主管",
     "script_range": "0:21–0:37", "target_seconds": 16,
     "script_source": "0:21—0:37｜深夜，办公室·工位隔断",
     "shot_ids": ["sh006", "sh007", "sh008"]},
    {"id": "seq03", "order": 3, "title": "清晨出门",
     "script_range": "0:37–1:07", "target_seconds": 30,
     "script_source": "0:37—1:07｜清晨，母亲家·村口·汽车站",
     "shot_ids": ["sh009", "sh010", "sh011", "sh012", "sh013"]},
    {"id": "seq04", "order": 4, "title": "大巴与火车",
     "script_range": "1:07–1:15", "target_seconds": 8,
     "script_source": "1:07—1:15｜大巴→火车（旅途）",
     "shot_ids": ["sh014", "sh015"]},
    {"id": "seq05", "order": 5, "title": "站牌与闸机",
     "script_range": "1:15–1:45", "target_seconds": 30,
     "script_source": "1:15—1:45｜火车站出站口·地铁闸机",
     "shot_ids": ["sh016", "sh017", "sh018", "sh019", "sh020"]},
    {"id": "seq06", "order": 6, "title": "地铁与会议室",
     "script_range": "1:45–2:10", "target_seconds": 25,
     "script_source": "1:45—2:10｜地铁车厢·双线",
     "shot_ids": ["sh021", "sh022", "sh023", "sh024", "sh025"]},
    {"id": "seq07", "order": 7, "title": "站台事故",
     "script_range": "2:10–2:28", "target_seconds": 18,
     "script_source": "2:10—2:28｜地铁站台",
     "shot_ids": ["sh026", "sh027", "sh028", "sh029", "sh030"]},
    {"id": "seq08", "order": 8, "title": "病房与回忆",
     "script_range": "2:28–3:09", "target_seconds": 41,
     "script_source": "2:28—3:09｜医院病房·回忆·定格",
     "shot_ids": ["sh031", "sh032", "sh033", "sh034", "sh035", "sh036", "sh037", "sh038"]},
]

# target_seconds 为导演窗口。台词起止待 WAV 实测后填。
SHOTS = [
    {"id": "sh001", "sequence_id": "seq01", "order": 1, "target_seconds": 6,
     "title": "办公室中景：接听",
     "shot_size": "中景", "camera": "办公室机位A", "cut_reason": "切母亲家中近景",
     "location_id": "loc_office_night", "location_variant_id": "loc_office_night_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "wangguifen", "on_screen": False, "voice": True}],
     "props": [{"asset_id": "prop_phone_lin", "state": "ringing_then_held"}],
     "action": "手机震动、接起；母亲画外：「川，还在加班吗……马上中秋节，你回家吗？」接听后维持持机，尚未回答。",
     "entry_state": "林川独自加班，手机在桌面",
     "exit_state": "林川持机贴耳，正在听母亲问话",
     "conditioning_mode": "first_only",
     "utterance_ids": ["ut001"],
     "legacy_scene_ids": ["sc01", "sc26"],
     "start_legacy": "keyframes/kf_sc01_start.png",
     "end_legacy": "keyframes/kf_sc01_end.png"},
    {"id": "sh002", "sequence_id": "seq01", "order": 2, "target_seconds": 3,
     "title": "母亲家近景：问加班、问中秋",
     "shot_size": "近景", "camera": "家中夜间机位A", "cut_reason": "回办公室",
     "location_id": "loc_home", "location_variant_id": "loc_home_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "held_to_ear"},
               {"asset_id": "prop_mooncake", "state": "on_table"}],
     "action": "同一句电话交叉剪：王桂芬出镜说「川，还在加班吗……马上中秋节，你回家吗？」鸡蛋、月饼在场。说完等待。",
     "entry_state": "王桂芬坐方桌旁持机，暖黄台灯",
     "exit_state": "问完，仍持机等待",
     "conditioning_mode": "first_only",
     "utterance_ids": ["ut001"],
     "legacy_scene_ids": ["sc02"],
     "start_legacy": "keyframes/kf_sc02_start.png"},
    {"id": "sh003", "sequence_id": "seq01", "order": 3, "target_seconds": 5.5,
     "title": "办公室：可能加班，主管走近",
     "shot_size": "中景", "camera": "办公室机位A，后景可见入口", "cut_reason": "主管到身旁切过肩",
     "location_id": "loc_office_night", "location_variant_id": "loc_office_night_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "zhuguan", "on_screen": True, "enter": "对白后半从入口走近"}],
     "props": [{"asset_id": "prop_phone_lin", "state": "held_to_ear"}],
     "action": "林川疲惫：「对啊，老妈，我还在忙，中秋节我可能要加班。」主管在对白后半从入口走近，不从首帧凭空出现。",
     "entry_state": "林川持机通话，入口无人",
     "exit_state": "主管已走近至入口/身旁，林川仍持机",
     "conditioning_mode": "first_only",
     "utterance_ids": ["ut002"],
     "legacy_scene_ids": ["sc03"],
     "start_legacy": "keyframes/kf_sc01_end.png",
     "end_legacy": "keyframes/kf_sc03_start.png"},
    {"id": "sh004", "sequence_id": "seq01", "order": 4, "target_seconds": 3.5,
     "title": "过肩：先挂了",
     "shot_size": "过肩/侧面", "camera": "办公室机位B", "cut_reason": "切母亲反应",
     "location_id": "loc_office_night", "location_variant_id": "loc_office_night_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "zhuguan", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_lin", "state": "held_then_hangup"}],
     "action": "林川瞥主管：「妈！主管找我了，回头再说啊，先挂了。」随后挂断。不重复来人动作。",
     "entry_state": "主管已在身旁，林川仍持机",
     "exit_state": "电话已挂，林川仍坐工位，主管在旁",
     "conditioning_mode": "first_only",
     "utterance_ids": ["ut003"],
     "legacy_scene_ids": ["sc27"],
     "start_legacy": "keyframes/kf_sc03_start.png"},
    {"id": "sh005", "sequence_id": "seq01", "order": 5, "target_seconds": 3,
     "title": "母亲反应",
     "shot_size": "中近景", "camera": "家中夜间机位A", "cut_reason": "切办公室双人",
     "location_id": "loc_home", "location_variant_id": "loc_home_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "held_after_busy_tone"}],
     "action": "忙音，母亲握着手机，笑意收住；短停顿。无新增对白，无需口型。",
     "entry_state": "仍持机，刚听完儿子要挂",
     "exit_state": "笑意收住，握机愣住",
     "conditioning_mode": "first_only",
     "utterance_ids": [],
     "legacy_scene_ids": [],
     "start_legacy": "keyframes/kf_sc02_start.png"},
    {"id": "sh006", "sequence_id": "seq02", "order": 1, "target_seconds": 4,
     "title": "放下手机交差",
     "shot_size": "双人中景", "camera": "办公室机位A", "cut_reason": "切主管为主构图",
     "location_id": "loc_office_night", "location_variant_id": "loc_office_night_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "zhuguan", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_lin", "state": "ear_to_desk"}],
     "action": "林川放下手机、看屏幕：「第一版方案改的差不多了。」与 sh004 离开状态相容。",
     "entry_state": "电话已挂，主管在旁，手机仍可能在手中",
     "exit_state": "手机在桌面，林川看屏幕，主管在旁",
     "conditioning_mode": "first_only",
     "utterance_ids": ["ut006"],
     "legacy_scene_ids": ["sc04"],
     "start_legacy": "keyframes/kf_sc03_start.png"},
    {"id": "sh007", "sequence_id": "seq02", "order": 2, "target_seconds": 7,
     "title": "主管交代后离开",
     "shot_size": "双人，主管为主", "camera": "办公室机位B", "cut_reason": "主管离开后切林川独自",
     "location_id": "loc_office_night", "location_variant_id": "loc_office_night_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "zhuguan", "on_screen": True, "exit": "说完转身离开"},
              {"asset_id": "linchuan", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_lin", "state": "on_desk"}],
     "action": "主管一口气：「小林，摇一摇跳到下一个应用，只是起点。客户要的是场景闭环，活跃价值得留在客户手里。方案明早给我。」指屏幕、收手、离开。同镜一句，不要拆成两条。",
     "entry_state": "手机在桌，主管在旁",
     "exit_state": "主管已离开画面，林川独自对着屏幕",
     "conditioning_mode": "first_only",
     "utterance_ids": ["ut007"],
     "legacy_scene_ids": ["sc28", "sc05"],
     "start_legacy": "keyframes/kf_sc04_start.png"},
    {"id": "sh008", "sequence_id": "seq02", "order": 3, "target_seconds": 5,
     "title": "林川自语",
     "shot_size": "近景", "camera": "办公室机位C", "cut_reason": "段落结束，切清晨",
     "location_id": "loc_office_night", "location_variant_id": "loc_office_night_night",
     "era_id": "present_night",
     "cast": [{"asset_id": "linchuan", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_lin", "state": "on_desk"}],
     "action": "挠头、低声：「业务闭环，你倒是说怎么闭环呀。」从主管已经离开开始。",
     "entry_state": "主管已离开，林川独自",
     "exit_state": "挠头结束，仍对着屏幕",
     "conditioning_mode": "first_only",
     "utterance_ids": ["ut009"],
     "legacy_scene_ids": ["sc29"],
     "start_legacy": "keyframes/kf_sc05_start.png"},
    {"id": "sh009", "sequence_id": "seq03", "order": 1, "target_seconds": 5,
     "title": "装蛋与生日纸条", "shot_size": "中景", "camera": "家中清晨机位",
     "location_id": "loc_home", "location_variant_id": "loc_home_morning",
     "era_id": "present_morning",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_basket", "state": "packing"},
               {"asset_id": "prop_mooncake", "state": "beside_bundle"},
               {"asset_id": "prop_note", "state": "birthday_note_into_clothes"}],
     "action": "把鸡蛋码进蓝布包袱，生日纸条压进衣物，系紧。",
     "entry_state": "清晨家中，包袱未系", "exit_state": "包袱系紧抱起",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc06"], "gap": "清晨变体未登记，不可用夜间图直接覆盖"},
    {"id": "sh010", "sequence_id": "seq03", "order": 2, "target_seconds": 7,
     "title": "村口问路", "shot_size": "中景", "camera": "村口土路",
     "location_id": "loc_village_road", "location_variant_id": "loc_village_road_morning",
     "era_id": "present_morning",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "cunzhang", "on_screen": True}],
     "props": [{"asset_id": "prop_basket", "state": "held"}],
     "action": "问路；村长说正好有空捎到镇上。对白与动作可并行。",
     "entry_state": "薄雾土路", "exit_state": "准备上车",
     "conditioning_mode": "first_only", "utterance_ids": ["ut010", "ut011"],
     "legacy_scene_ids": ["sc07"]},
    {"id": "sh011", "sequence_id": "seq03", "order": 3, "target_seconds": 6,
     "title": "三轮车上说路线", "shot_size": "中景", "camera": "车斗随行",
     "location_id": "loc_village_road", "location_variant_id": "loc_village_road_morning",
     "era_id": "present_morning",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "cunzhang", "on_screen": True}],
     "props": [{"asset_id": "prop_basket", "state": "held_in_bucket"}],
     "action": "三轮驶过村道；村长喊换乘。电动三轮需正式资产。",
     "entry_state": "已坐上车斗", "exit_state": "仍在车上接近车站",
     "conditioning_mode": "first_only", "utterance_ids": ["ut012"],
     "legacy_scene_ids": ["sc08"], "gap": "电动三轮未登记"},
    {"id": "sh012", "sequence_id": "seq03", "order": 4, "target_seconds": 6,
     "title": "汽车站递纸条", "shot_size": "中近景", "camera": "汽车站",
     "location_id": "loc_bus_station", "location_variant_id": "loc_bus_station_morning",
     "era_id": "present_morning",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "cunzhang", "on_screen": True}],
     "props": [{"asset_id": "prop_note", "state": "handed_route_slip"},
               {"asset_id": "prop_phone_wang", "state": "map_app_installed"}],
     "action": "村长塞纸条、给旧手机装地图。",
     "entry_state": "已到汽车站", "exit_state": "纸条在母亲手里",
     "conditioning_mode": "first_only", "utterance_ids": ["ut013"],
     "legacy_scene_ids": ["sc09"]},
    {"id": "sh013", "sequence_id": "seq03", "order": 5, "target_seconds": 6,
     "title": "看手机地图", "shot_size": "近景", "camera": "汽车站",
     "location_id": "loc_bus_station", "location_variant_id": "loc_bus_station_morning",
     "era_id": "present_morning",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "map_open"},
               {"asset_id": "prop_note", "state": "in_hand"}],
     "action": "打开地图看了半天，一知半解地点头。",
     "entry_state": "纸条与手机都在手里", "exit_state": "点头，准备上车",
     "conditioning_mode": "first_only", "utterance_ids": ["ut014"],
     "legacy_scene_ids": ["sc09"]},
    {"id": "sh014", "sequence_id": "seq04", "order": 1, "target_seconds": 3,
     "title": "大巴靠窗", "shot_size": "近景", "camera": "大巴车内",
     "location_id": "loc_bus_interior", "location_variant_id": "loc_bus_interior_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_basket", "state": "held"}],
     "action": "坐大巴靠窗望外。大巴车内地点候选待补。",
     "entry_state": "已坐大巴", "exit_state": "仍望窗外",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc10"], "gap": "缺大巴车内地点"},
    {"id": "sh015", "sequence_id": "seq04", "order": 2, "target_seconds": 5,
     "title": "火车窗练习祝福", "shot_size": "近景", "camera": "绿皮火车",
     "location_id": "loc_train", "location_variant_id": "loc_train_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_basket", "state": "held_tight"}],
     "action": "切火车窗，田野变高楼；轻声练习生日快乐。",
     "entry_state": "从大巴切到火车，仍抱包袱", "exit_state": "练习完，抱紧包袱",
     "conditioning_mode": "first_only", "utterance_ids": ["ut015"],
     "legacy_scene_ids": ["sc10"]},
    {"id": "sh016", "sequence_id": "seq05", "order": 1, "target_seconds": 5,
     "title": "停运信息", "shot_size": "中景", "camera": "出站口站牌",
     "location_id": "loc_bus_stop", "location_variant_id": "loc_bus_stop_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_note", "state": "compared_to_sign"},
               {"asset_id": "prop_bus_sign", "state": "removed_do_not_restore"}],
     "action": "停运告示用已审场景配可控文字层；不得自动恢复已移除站牌道具。路线编号待剧本审核。",
     "entry_state": "出站口", "exit_state": "看不懂，站牌下等",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc11"]},
    {"id": "sh017", "sequence_id": "seq05", "order": 2, "target_seconds": 7,
     "title": "周野定路线", "shot_size": "双人中景", "camera": "站牌旁",
     "location_id": "loc_bus_stop", "location_variant_id": "loc_bus_stop_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "zhouye", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "map_route_set"}],
     "action": "周野接过碎屏手机，定好路线：「阿姨，看蓝点，跟着这条线走。」",
     "entry_state": "母亲等车", "exit_state": "地图已定路线",
     "conditioning_mode": "first_only", "utterance_ids": ["ut016"],
     "legacy_scene_ids": ["sc12"]},
    {"id": "sh018", "sequence_id": "seq05", "order": 3, "target_seconds": 5,
     "title": "闸机犯难", "shot_size": "中景", "camera": "地铁闸机",
     "location_id": "loc_subway_gate", "location_variant_id": "loc_subway_gate_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "at_gate"}],
     "action": "闸机前又犯难。",
     "entry_state": "到达闸机", "exit_state": "停在闸机前",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc13"]},
    {"id": "sh019", "sequence_id": "seq05", "order": 4, "target_seconds": 5,
     "title": "小雨刷码", "shot_size": "双人中近景", "camera": "闸机",
     "location_id": "loc_subway_gate", "location_variant_id": "loc_subway_gate_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "xiaoyu", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "ride_app_open"}],
     "action": "小雨打开乘车 APP，刷开闸机。",
     "entry_state": "母亲停在闸机前", "exit_state": "闸机已开",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc13"]},
    {"id": "sh020", "sequence_id": "seq05", "order": 5, "target_seconds": 8,
     "title": "小雨提醒", "shot_size": "近景", "camera": "闸机内侧",
     "location_id": "loc_subway_gate", "location_variant_id": "loc_subway_gate_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "xiaoyu", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "in_hand"}],
     "action": "小雨提醒不要点取消、不要晃手机。",
     "entry_state": "已刷开", "exit_state": "母亲点头进站",
     "conditioning_mode": "first_only", "utterance_ids": ["ut017"],
     "legacy_scene_ids": ["sc14"]},
    {"id": "sh021", "sequence_id": "seq06", "order": 1, "target_seconds": 6,
     "title": "广告跳转", "shot_size": "近景屏幕+人", "camera": "车厢座位",
     "location_id": "loc_subway_car", "location_variant_id": "loc_subway_car_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "ad_then_shop_then_video"}],
     "action": "打开地图，摇一摇广告，点×进购物再进短视频。屏幕文字后期替换。",
     "entry_state": "列车启动，地图打开", "exit_state": "页面已跳转",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc15"]},
    {"id": "sh022", "sequence_id": "seq06", "order": 2, "target_seconds": 5,
     "title": "母亲求助", "shot_size": "近景", "camera": "车厢",
     "location_id": "loc_subway_car", "location_variant_id": "loc_subway_car_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "ad_loop"}],
     "action": "回到乘车 APP，广告再弹：「我只想看路……」",
     "entry_state": "仍被广告困住", "exit_state": "说完，屏幕仍亮",
     "conditioning_mode": "first_only", "utterance_ids": ["ut018"],
     "legacy_scene_ids": ["sc15"]},
    {"id": "sh023", "sequence_id": "seq06", "order": 3, "target_seconds": 5,
     "title": "会议室静音", "shot_size": "中景", "camera": "会议室",
     "location_id": "loc_meeting_room", "location_variant_id": "loc_meeting_room_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "zhuguan", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_lin", "state": "mom_call_silenced"}],
     "action": "林川开会，妈妈来电，按下静音。会议室地点待补。",
     "entry_state": "会议中", "exit_state": "来电已静音",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc16"], "gap": "缺会议室地点；禁止用地铁地点混母亲与林川"},
    {"id": "sh024", "sequence_id": "seq06", "order": 4, "target_seconds": 5,
     "title": "车窗倒影", "shot_size": "中近景", "camera": "车厢窗",
     "location_id": "loc_subway_car", "location_variant_id": "loc_subway_car_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "ad_glow_on_window"}],
     "action": "广告光映在车窗，户外广告牌掠过。",
     "entry_state": "回到车厢", "exit_state": "脸与广告重叠",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc17"]},
    {"id": "sh025", "sequence_id": "seq06", "order": 5, "target_seconds": 4,
     "title": "广告重叠", "shot_size": "特写/叠化", "camera": "车窗",
     "location_id": "loc_subway_car", "location_variant_id": "loc_subway_car_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "ad_glow"}],
     "action": "广告、车窗、母亲的脸不断重叠。",
     "entry_state": "倒影已建立", "exit_state": "列车将到站",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc17"]},
    {"id": "sh026", "sequence_id": "seq07", "order": 1, "target_seconds": 4,
     "title": "下车踉跄", "shot_size": "中景", "camera": "站台",
     "location_id": "loc_platform", "location_variant_id": "loc_platform_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_basket", "state": "held"},
               {"asset_id": "prop_phone_wang", "state": "in_hand"}],
     "action": "走下车，脚步踉跄。",
     "entry_state": "车门打开", "exit_state": "站在站台，不稳",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc18"]},
    {"id": "sh027", "sequence_id": "seq07", "order": 2, "target_seconds": 3,
     "title": "手机滑落", "shot_size": "手部特写接中景", "camera": "站台",
     "location_id": "loc_platform", "location_variant_id": "loc_platform_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "slips_to_ground"}],
     "action": "广告遮住路线，点取消又跳转，手机滑落。",
     "entry_state": "手机在手中", "exit_state": "手机在地面",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc19"]},
    {"id": "sh028", "sequence_id": "seq07", "order": 3, "target_seconds": 4,
     "title": "包袱翻倒蛋碎", "shot_size": "中近景", "camera": "站台地面",
     "location_id": "loc_platform", "location_variant_id": "loc_platform_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_basket", "state": "open_spilled"},
               {"asset_id": "prop_eggs_broken", "state": "broken_on_floor"}],
     "action": "包袱翻倒，鸡蛋碎。道具状态：闭合→打开，完整→碎裂。",
     "entry_state": "包袱闭合，蛋完整", "exit_state": "包袱打开，蛋碎",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc19"], "gap": "鸡蛋碎裂状态未登记"},
    {"id": "sh029", "sequence_id": "seq07", "order": 4, "target_seconds": 3,
     "title": "母亲倒下", "shot_size": "中景", "camera": "站台",
     "location_id": "loc_platform", "location_variant_id": "loc_platform_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "on_ground_playing_ad"}],
     "action": "伸手想捡手机，眼前发黑倒下。",
     "entry_state": "弯腰去捡", "exit_state": "已倒地",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc20"]},
    {"id": "sh030", "sequence_id": "seq07", "order": 5, "target_seconds": 4,
     "title": "工作人员拨号", "shot_size": "中景", "camera": "站台",
     "location_id": "loc_platform", "location_variant_id": "loc_platform_day",
     "era_id": "present_day",
     "cast": [{"asset_id": "wangguifen", "on_screen": True, "state": "unconscious"},
              {"asset_id": "char_staff", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "contact_son_dialing"}],
     "action": "工作人员拨通联系人「儿子：林川」。配角按镜头登记，不自动当主要人物。",
     "entry_state": "母亲倒地", "exit_state": "正在拨号",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc20"], "gap": "站台工作人员未登记"},
    {"id": "sh031", "sequence_id": "seq08", "order": 1, "target_seconds": 6,
     "title": "病房醒来", "shot_size": "中近景", "camera": "病房日间",
     "location_id": "loc_hospital", "location_variant_id": "loc_hospital_wake",
     "era_id": "present_midautumn",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "linchuan", "on_screen": True}],
     "props": [{"asset_id": "prop_mooncake", "state": "unopened_on_cabinet"},
               {"asset_id": "prop_phone_wang", "state": "still_on"}],
     "action": "中秋，王桂芬醒来：「儿子，给你添麻烦了。」林川没有回答。医院醒来光线。",
     "entry_state": "病床，缓缓睁眼", "exit_state": "已醒，林川在旁不答",
     "conditioning_mode": "first_only", "utterance_ids": ["ut019"],
     "legacy_scene_ids": ["sc21"]},
    {"id": "sh032", "sequence_id": "seq08", "order": 2, "target_seconds": 5,
     "title": "广告闭环", "shot_size": "特写屏幕", "camera": "床头",
     "location_id": "loc_hospital", "location_variant_id": "loc_hospital_wake",
     "era_id": "present_midautumn",
     "cast": [{"asset_id": "linchuan", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "ad_loop_unexitable"}],
     "action": "碎屏手机广告跳购物再跳短视频，再摇一摇。屏幕后期替换。",
     "entry_state": "手机仍亮", "exit_state": "林川伸手去关",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc21"]},
    {"id": "sh033", "sequence_id": "seq08", "order": 3, "target_seconds": 5,
     "title": "儿子对白", "shot_size": "近景", "camera": "病床旁",
     "location_id": "loc_hospital", "location_variant_id": "loc_hospital_wake",
     "era_id": "present_midautumn",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "wangguifen", "on_screen": True}],
     "props": [{"asset_id": "prop_phone_wang", "state": "held_by_son"}],
     "action": "林川崩溃抓住手机：「没事，妈……你只是迷路了而已。」",
     "entry_state": "关不掉广告", "exit_state": "说完，提示音将变车铃",
     "conditioning_mode": "first_only", "utterance_ids": ["ut020"],
     "legacy_scene_ids": ["sc22"]},
    {"id": "sh034", "sequence_id": "seq08", "order": 4, "target_seconds": 6,
     "title": "回忆寻找", "shot_size": "中景", "camera": "童年街道黄昏",
     "location_id": "loc_street_dusk", "location_variant_id": "loc_street_dusk_memory",
     "era_id": "childhood_dusk",
     "cast": [{"asset_id": "wangguifen_young", "on_screen": True, "person_id": "wangguifen"},
              {"asset_id": "linchuan_child", "on_screen": False, "person_id": "linchuan"}],
     "props": [],
     "action": "年轻王桂芬满街奔跑喊川川。回忆调色靠 era_id，不靠 sc20 数字。人群用背景人物规则。",
     "entry_state": "自行车铃转入回忆", "exit_state": "仍在寻找",
     "conditioning_mode": "first_only", "utterance_ids": ["ut021"],
     "legacy_scene_ids": ["sc23"]},
    {"id": "sh035", "sequence_id": "seq08", "order": 5, "target_seconds": 5,
     "title": "回忆重逢", "shot_size": "中近景", "camera": "墙角",
     "location_id": "loc_street_dusk", "location_variant_id": "loc_street_dusk_memory",
     "era_id": "childhood_dusk",
     "cast": [{"asset_id": "wangguifen_young", "on_screen": True, "person_id": "wangguifen"},
              {"asset_id": "linchuan_child", "on_screen": True, "person_id": "linchuan"}],
     "props": [],
     "action": "在墙角找到小林川，抱紧：「别怕，妈找着你了。」",
     "entry_state": "孩子在墙角", "exit_state": "抱紧",
     "conditioning_mode": "first_only", "utterance_ids": ["ut022"],
     "legacy_scene_ids": ["sc24"]},
    {"id": "sh036", "sequence_id": "seq08", "order": 6, "target_seconds": 6,
     "title": "手部匹配", "shot_size": "特写", "camera": "手叠化",
     "location_id": "loc_hospital", "location_variant_id": "loc_hospital_wake",
     "era_id": "present_midautumn",
     "cast": [{"asset_id": "wangguifen", "on_screen": True},
              {"asset_id": "wangguifen_young", "on_screen": True, "person_id": "wangguifen"}],
     "props": [],
     "action": "年轻母亲抱紧的手与病床上苍老的手重叠。剪辑完成，不让生成模型一次做完。",
     "entry_state": "回忆拥抱", "exit_state": "回到病床手部",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc25"]},
    {"id": "sh037", "sequence_id": "seq08", "order": 7, "target_seconds": 4,
     "title": "满月", "shot_size": "窗外+人物", "camera": "病房满月光线",
     "location_id": "loc_hospital", "location_variant_id": "loc_hospital_moon",
     "era_id": "present_midautumn",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "wangguifen", "on_screen": True}],
     "props": [],
     "action": "窗外中秋满月升起。林川看着母亲落泪。医院满月光线，不得与醒来光线混用。",
     "entry_state": "手部叠化结束", "exit_state": "对视落泪",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc25"], "gap": "医院满月光线未登记"},
    {"id": "sh038", "sequence_id": "seq08", "order": 8, "target_seconds": 4,
     "title": "定格黑屏", "shot_size": "定格", "camera": "病房",
     "location_id": "loc_hospital", "location_variant_id": "loc_hospital_moon",
     "era_id": "present_midautumn",
     "cast": [{"asset_id": "linchuan", "on_screen": True},
              {"asset_id": "wangguifen", "on_screen": True}],
     "props": [],
     "action": "画面定格，黑屏。",
     "entry_state": "落泪对视", "exit_state": "黑屏",
     "conditioning_mode": "first_only", "utterance_ids": [],
     "legacy_scene_ids": ["sc25"]},
]

UTTERANCES = [
    {"id": "ut001", "speaker": "wangguifen", "text": "川，还在加班吗……马上中秋节，你回家吗？",
     "emotion": "关切", "source": "state", "legacy_scene_id": "sc01"},
    {"id": "ut002", "speaker": "linchuan", "text": "对啊，老妈，我还在忙，中秋节我可能要加班。",
     "emotion": "疲惫", "source": "state", "legacy_scene_id": "sc26"},
    {"id": "ut003", "speaker": "linchuan", "text": "妈！主管找我了，回头再说啊，先挂了。",
     "emotion": "急促", "source": "state", "legacy_scene_id": "sc27"},
    {"id": "ut006", "speaker": "linchuan", "text": "第一版方案改的差不多了。",
     "emotion": "交差", "source": "state", "legacy_scene_id": "sc04"},
    {"id": "ut007", "speaker": "zhuguan",
     "text": "小林，摇一摇跳到下一个应用，只是起点。客户要的是场景闭环，活跃价值得留在客户手里。方案明早给我。",
     "emotion": "交代", "source": "state", "legacy_scene_id": "sc28"},
    {"id": "ut009", "speaker": "linchuan", "text": "业务闭环，你倒是说怎么闭环呀。",
     "emotion": "烦躁低声", "source": "state", "legacy_scene_id": "sc29"},
    {"id": "ut010", "speaker": "wangguifen", "text": "他村长，去A市，我该咋走啊？",
     "emotion": "问路", "source": "state", "legacy_scene_id": "sc07"},
    {"id": "ut011", "speaker": "cunzhang", "text": "巧了，我正好有空，捎你到镇上车站，路上跟你说。",
     "emotion": "热心", "source": "state", "legacy_scene_id": "sc07"},
    {"id": "ut012", "speaker": "cunzhang", "text": "到了城里，先坐大巴到火车站，再找地铁，跟着牌子走就行。",
     "emotion": "边开边喊", "source": "state", "legacy_scene_id": "sc08"},
    {"id": "ut013", "speaker": "cunzhang", "text": "我在手机地图上查的，都写在这纸条上了，不认路就在地图上搜。",
     "emotion": "叮嘱", "source": "state", "legacy_scene_id": "sc09"},
    {"id": "ut014", "speaker": "wangguifen", "text": "哎，哎，中。",
     "emotion": "一知半解", "source": "state", "legacy_scene_id": "sc09"},
    {"id": "ut015", "speaker": "wangguifen", "text": "川川，生日快乐。",
     "emotion": "轻声练习", "source": "state", "legacy_scene_id": "sc10"},
    {"id": "ut016", "speaker": "zhouye", "text": "阿姨，看蓝点，跟着这条线走。",
     "emotion": "清楚", "source": "state", "legacy_scene_id": "sc12"},
    {"id": "ut017", "speaker": "xiaoyu", "text": "奶奶，广告出来不要点「取消」，也不要晃手机，会跳到别的地方。",
     "emotion": "认真", "source": "state", "legacy_scene_id": "sc14"},
    {"id": "ut018", "speaker": "wangguifen", "text": "我只想看路……",
     "emotion": "无助", "source": "state", "legacy_scene_id": "sc15"},
    {"id": "ut019", "speaker": "wangguifen", "text": "儿子，给你添麻烦了。",
     "emotion": "虚弱", "source": "state", "legacy_scene_id": "sc21"},
    {"id": "ut020", "speaker": "linchuan", "text": "没事，妈……你只是迷路了而已。",
     "emotion": "崩溃克制", "source": "state", "legacy_scene_id": "sc22"},
    {"id": "ut021", "speaker": "wangguifen_young", "text": "川川——川川！",
     "emotion": "焦急", "source": "state", "legacy_scene_id": "sc23"},
    {"id": "ut022", "speaker": "wangguifen_young", "text": "别怕，妈找着你了。",
     "emotion": "心疼", "source": "state", "legacy_scene_id": "sc24"},
]

SCRIPT_ONLY_LINES = []

ROUTE_DIFF = {
    "script_sign": "52路暂停运营",
    "approved_note_image": "坐大巴转火车，再转公交车15路",
    "cunzhang_spoken": "先坐大巴到火车站，再找地铁",
    "candidate": "大巴→火车→原计划 15 路公交停运→改走地铁",
    "note": "需进入剧本差异审核，不在迁移时覆盖对白或资产",
}

MISSING_ASSETS = [
    {"id": "loc_home_morning", "type": "scene", "need": "母亲家清晨光线，不能用已批夜间图覆盖"},
    {"id": "loc_hospital_moon", "type": "scene", "need": "医院满月结尾光线，与醒来时区分"},
    {"id": "loc_bus_interior", "type": "scene", "need": "大巴车内"},
    {"id": "loc_meeting_room", "type": "scene", "need": "会议室；禁止用地铁地点同时放母亲与林川"},
    {"id": "prop_tricycle", "type": "prop", "need": "电动三轮"},
    {"id": "prop_birthday_note", "type": "prop", "need": "生日快乐纸条；与路线纸条区分"},
    {"id": "prop_eggs_broken", "type": "prop", "need": "鸡蛋摔碎状态"},
    {"id": "prop_mug", "type": "prop", "need": "主管马克杯"},
    {"id": "char_staff", "type": "character", "need": "站台工作人员，受控配角"},
]

PERSON_LINKS = {
    "wangguifen": ["wangguifen", "wangguifen_young"],
    "linchuan": ["linchuan", "linchuan_child"],
}


def build_utterances():
    out = []
    for u in UTTERANCES:
        item = dict(u)
        item.setdefault("voice_revision_id", None)
        item.setdefault("wav", None)
        item.setdefault("measured_seconds", None)
        item.setdefault("status", "pending")
        item.setdefault("sequence_in_sample", None)
        item.setdefault("sequence_out_sample", None)
        out.append(item)
    return out


def build_sequences():
    out = []
    for seq in SEQUENCES:
        s = dict(seq)
        s["target_frames"] = seconds_to_frames(s["target_seconds"])
        s["status"] = "draft"
        s["budget_review_revision"] = 0
        out.append(s)
    return out


def build_shots():
    out = []
    for raw in SHOTS:
        sh = dict(raw)
        sh["target_frames"] = seconds_to_frames(sh.pop("target_seconds"))
        sh["status"] = "draft"
        sh["validity"] = "current"
        start_file = sh.pop("start_legacy", "")
        end_file = sh.pop("end_legacy", "")
        sh["start"] = {
            "image": start_file, "status": "review" if start_file else "pending",
            "validity": "stale" if start_file else "current",
            "note": "旧图迁入候选，构图/动作/时长需按新镜头重审" if start_file else "",
        }
        sh["end"] = {
            "image": end_file,
            "status": "review" if end_file else "removed",
            "validity": "stale" if end_file else "current",
            "note": "尾帧仅作审核目标，是否参与推理看 conditioning_mode" if end_file else "",
        }
        sh["video"] = {"file": "", "status": "pending", "validity": "current"}
        sh["storyboard"] = {"status": "pending"}
        out.append(sh)
    return out


def attach_to_state(state):
    state["sequences"] = build_sequences()
    state["shots"] = build_shots()
    state["utterances"] = build_utterances()
    _reflow_timelines(state)
    state["planning"] = recompute(state)
    return state
